# Generated by Django 5.1.1 on 2024-09-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=30, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategiriya',
                'verbose_name_plural': 'Kategorilar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Taglar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rilishlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shildi")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilandi')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='Rasm')),
                ('is_published', models.BooleanField(default=True, verbose_name="Ko'rinishi")),
                ('author', models.CharField(max_length=50, verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Kategoriya')),
                ('tags', models.ManyToManyField(to='news.tag', verbose_name='Etiketlar')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
