# Generated by Django 5.1.1 on 2024-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='quotes',
            field=models.TextField(default=1, verbose_name='Iqtibos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Yozuvchi'),
        ),
    ]
