# Generated by Django 5.1.1 on 2024-09-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_quotes_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
