# Generated by Django 5.1.1 on 2024-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('confirmation_code', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Confirmation code',
                'verbose_name_plural': 'Confirmation codes',
            },
        ),
    ]
